language: rust

install:
  - git clone https://github.com/niklasso/minisat.git minisat
  - cd minisat
  - make
  - cd ..
  - export PATH=./minisat/build/release/bin:$PATH

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --release --verbose -- --ignored --nocapture
