[package]
name = "minisat-rust"
version = "0.0.1"
authors = ["Alexander Mishunin <alexander.mishunin@gmail.com>"]

[profile.dev]
opt-level = 0
debug = true

[dependencies]
time = "*"
getopts = "0.2"
vec_map = "0.4.0"
